[workspace]
members = [
        "zebra-chain",
        "zebra-network",
        "zebra-storage",
        "zebra-script",
        "zebra-consensus",
        "zebra-rpc",
        "zebra-client",
        "zebrad",
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"