[package]
name = "zebra-network"
version = "0.1.0"
authors = ["Henry de Valence <hdevalence@hdevalence.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.2"
bytes = "0.4"
rand = "0.7"
byteorder = "1.3"
chrono = "0.4"
failure = "0.1"
tokio = "=0.2.0-alpha.5"
# This revision specification keeps us just behind the change from pin-project
# 0.4.0-alpha.11 to ^0.4, which we can't use until tokio, hyper, etc. also all change, because
# Cargo insists on unifying dependencies in the same semver range.
tower = { git = "https://github.com/tower-rs/tower", rev = "d5b36b54a50cceac7efb6292480424c8dd03f7ec" }
tracing = { git = "https://github.com/tokio-rs/tracing" }
tracing-futures = { git = "https://github.com/tokio-rs/tracing", features = ["tokio-alpha"], default-features = false }
futures-preview = { version = "=0.3.0-alpha.18", features = ["async-await", "nightly"] }


zebra-chain = { path = "../zebra-chain" }
